-- Seed full catalog into Supabase (keeps Sunflower Field).
-- Run once in Supabase → SQL Editor → Run

-- Remove prior catalog rows that point at the Vercel site (safe re-run)
delete from public.photos
where public_url like 'https://fatni-photography.vercel.app/%';

insert into public.photos (title, storage_path, public_url, categories, night_kind, sort_order) values
  ('Aerial Panorama', 'images/DJI_0464-HDR-Pano-Edit.jpg', 'https://fatni-photography.vercel.app/images/DJI_0464-HDR-Pano-Edit.jpg', ARRAY['Urban']::text[], null, 0),
  ('Aerial View', 'images/DJI_0117-HDR-Edit.jpg', 'https://fatni-photography.vercel.app/images/DJI_0117-HDR-Edit.jpg', ARRAY['Nature']::text[], null, 1),
  ('Coastal Cove', 'images/coastal-cove.jpg', 'https://fatni-photography.vercel.app/images/coastal-cove.jpg', ARRAY['Nature']::text[], null, 3),
  ('Trees', 'images/trees.jpeg', 'https://fatni-photography.vercel.app/images/trees.jpeg', ARRAY['Nature']::text[], null, 4),
  ('Valley Light', 'images/A7303942-Edit2.jpg', 'https://fatni-photography.vercel.app/images/A7303942-Edit2.jpg', ARRAY['Nature']::text[], null, 5),
  ('Coastal Moon', 'images/after-dark/1322EAC0-7E67-47C5-8FC4-6A8D285E561C.jpg', 'https://fatni-photography.vercel.app/images/after-dark/1322EAC0-7E67-47C5-8FC4-6A8D285E561C.jpg', ARRAY['Nature']::text[], null, 6),
  ('Arch View', 'images/after-dark/5F0A7A9B-056C-4494-A5B2-9670B3596602.jpg', 'https://fatni-photography.vercel.app/images/after-dark/5F0A7A9B-056C-4494-A5B2-9670B3596602.jpg', ARRAY['Nature']::text[], null, 7),
  ('Sea Stacks', 'images/after-dark/7E7A53E3-49A2-4BAA-8967-255434470242.jpg', 'https://fatni-photography.vercel.app/images/after-dark/7E7A53E3-49A2-4BAA-8967-255434470242.jpg', ARRAY['Nature']::text[], null, 9),
  ('Ice Shore', 'images/after-dark/DABA4D9F-F725-4871-ADF1-33567E2253C0.jpg', 'https://fatni-photography.vercel.app/images/after-dark/DABA4D9F-F725-4871-ADF1-33567E2253C0.jpg', ARRAY['Nature']::text[], null, 11),
  ('Hillside Lights', 'images/after-dark/IMG_5539-1.jpg', 'https://fatni-photography.vercel.app/images/after-dark/IMG_5539-1.jpg', ARRAY['Nature']::text[], null, 12),
  ('Alpine Church', 'images/travel/alpine-church.jpg', 'https://fatni-photography.vercel.app/images/travel/alpine-church.jpg', ARRAY['Nature']::text[], null, 13),
  ('Mountain Village', 'images/travel/mountain-village.jpg', 'https://fatni-photography.vercel.app/images/travel/mountain-village.jpg', ARRAY['Nature']::text[], null, 14),
  ('Palm Beach', 'images/travel/palm-beach.jpg', 'https://fatni-photography.vercel.app/images/travel/palm-beach.jpg', ARRAY['Nature']::text[], null, 15),
  ('Sunset Shore', 'images/travel/sunset-shore.jpg', 'https://fatni-photography.vercel.app/images/travel/sunset-shore.jpg', ARRAY['Nature']::text[], null, 16),
  ('Turquoise Coast', 'images/travel/turquoise-coast.jpg', 'https://fatni-photography.vercel.app/images/travel/turquoise-coast.jpg', ARRAY['Nature']::text[], null, 17),
  ('Island Outlook', 'images/travel/island-outlook.jpg', 'https://fatni-photography.vercel.app/images/travel/island-outlook.jpg', ARRAY['Nature']::text[], null, 18),
  ('Glacial Lagoon', 'images/travel/glacial-lagoon.jpg', 'https://fatni-photography.vercel.app/images/travel/glacial-lagoon.jpg', ARRAY['Nature']::text[], null, 19),
  ('Diamond Beach', 'images/travel/diamond-beach.jpg', 'https://fatni-photography.vercel.app/images/travel/diamond-beach.jpg', ARRAY['Nature']::text[], null, 20),
  ('Stag Portrait', 'images/nature/stag-portrait.jpg', 'https://fatni-photography.vercel.app/images/nature/stag-portrait.jpg', ARRAY['Nature']::text[], null, 21),
  ('Stags Clash', 'images/nature/stags-clash.jpg', 'https://fatni-photography.vercel.app/images/nature/stags-clash.jpg', ARRAY['Nature']::text[], null, 22),
  ('Deer Herd', 'images/nature/deer-herd.jpg', 'https://fatni-photography.vercel.app/images/nature/deer-herd.jpg', ARRAY['Nature']::text[], null, 23),
  ('Volcanic Peaks', 'images/nature/volcanic-peaks.jpg', 'https://fatni-photography.vercel.app/images/nature/volcanic-peaks.jpg', ARRAY['Nature']::text[], null, 24),
  ('Architecture', 'images/image_6483441.JPG', 'https://fatni-photography.vercel.app/images/image_6483441.JPG', ARRAY['Urban']::text[], null, 24),
  ('Night Marina', 'images/after-dark/0A9E1A4A-F5FB-4365-B12F-5BE1190395EB.jpg', 'https://fatni-photography.vercel.app/images/after-dark/0A9E1A4A-F5FB-4365-B12F-5BE1190395EB.jpg', ARRAY['Urban']::text[], null, 25),
  ('Light Ring', 'images/after-dark/12093E8F-8DE7-4233-96E1-28D8270D0C25.jpg', 'https://fatni-photography.vercel.app/images/after-dark/12093E8F-8DE7-4233-96E1-28D8270D0C25.jpg', ARRAY['Urban']::text[], null, 26),
  ('Blue Domes', 'images/after-dark/78F56291-F28E-42FD-9CDC-C4C33CF10530.jpg', 'https://fatni-photography.vercel.app/images/after-dark/78F56291-F28E-42FD-9CDC-C4C33CF10530.jpg', ARRAY['Urban']::text[], null, 27),
  ('City Lights', 'images/after-dark/A7302924.jpg', 'https://fatni-photography.vercel.app/images/after-dark/A7302924.jpg', ARRAY['Urban']::text[], null, 29),
  ('Hallgrimskirkja', 'images/after-dark/D28062C8-D542-4F6F-995E-DAD7790A7EC0.jpg', 'https://fatni-photography.vercel.app/images/after-dark/D28062C8-D542-4F6F-995E-DAD7790A7EC0.jpg', ARRAY['Urban']::text[], null, 30),
  ('Window Grid', 'images/after-dark/window-grid.jpg', 'https://fatni-photography.vercel.app/images/after-dark/window-grid.jpg', ARRAY['Urban']::text[], null, 32),
  ('Westminster Cyclist', 'images/urban/westminster-cyclist.jpg', 'https://fatni-photography.vercel.app/images/urban/westminster-cyclist.jpg', ARRAY['Urban']::text[], null, 33),
  ('Snow Street', 'images/urban/snow-street.jpg', 'https://fatni-photography.vercel.app/images/urban/snow-street.jpg', ARRAY['Urban']::text[], null, 34),
  ('Bus Reflection', 'images/urban/bus-reflection.jpg', 'https://fatni-photography.vercel.app/images/urban/bus-reflection.jpg', ARRAY['Urban']::text[], null, 35),
  ('Fortnum Night', 'images/urban/fortnum-night.jpg', 'https://fatni-photography.vercel.app/images/urban/fortnum-night.jpg', ARRAY['Urban']::text[], null, 36),
  ('Northern Lights', 'images/image_6483441-2.JPG', 'https://fatni-photography.vercel.app/images/image_6483441-2.JPG', ARRAY['Astro']::text[], null, 33),
  ('Star Trails Path', 'images/after-dark/26CDFA76-BFEA-4266-93DC-7A4BA3512337.jpg', 'https://fatni-photography.vercel.app/images/after-dark/26CDFA76-BFEA-4266-93DC-7A4BA3512337.jpg', ARRAY['Astro']::text[], null, 35),
  ('Star Road', 'images/after-dark/650CD8F4-159E-4E17-BF66-985E8DD1F47E.jpg', 'https://fatni-photography.vercel.app/images/after-dark/650CD8F4-159E-4E17-BF66-985E8DD1F47E.jpg', ARRAY['After Dark']::text[], null, 36),
  ('Comet Field', 'images/after-dark/A7308148-2.jpg', 'https://fatni-photography.vercel.app/images/after-dark/A7308148-2.jpg', ARRAY['Astro']::text[], null, 37),
  ('Aurora Watch', 'images/after-dark/C884E0B9-73BF-4C3B-AD2A-87F66FA575E1.jpg', 'https://fatni-photography.vercel.app/images/after-dark/C884E0B9-73BF-4C3B-AD2A-87F66FA575E1.jpg', ARRAY['Astro']::text[], null, 38),
  ('Aurora Cabin', 'images/after-dark/DD5ECB7C-5ACC-455F-B574-0B1976D659C4.jpg', 'https://fatni-photography.vercel.app/images/after-dark/DD5ECB7C-5ACC-455F-B574-0B1976D659C4.jpg', ARRAY['Astro']::text[], null, 39),
  ('Aurora Boat', 'images/after-dark/DECBAFBD-1653-43A6-80AE-E599A9E65066.jpg', 'https://fatni-photography.vercel.app/images/after-dark/DECBAFBD-1653-43A6-80AE-E599A9E65066.jpg', ARRAY['Astro']::text[], null, 40),
  ('Comet Tree', 'images/after-dark/DFB08D78-D13D-40B9-9154-898FBA4A7EEF.jpg', 'https://fatni-photography.vercel.app/images/after-dark/DFB08D78-D13D-40B9-9154-898FBA4A7EEF.jpg', ARRAY['Astro']::text[], null, 41),
  ('Aurora Lake', 'images/after-dark/E9823C88-C5A1-4102-B95E-13F2DD3F8371.jpg', 'https://fatni-photography.vercel.app/images/after-dark/E9823C88-C5A1-4102-B95E-13F2DD3F8371.jpg', ARRAY['Astro']::text[], null, 42),
  ('Kirkjufell Aurora', 'images/after-dark/_A736530-2-DeNoiseAI-severe-noise.jpg', 'https://fatni-photography.vercel.app/images/after-dark/_A736530-2-DeNoiseAI-severe-noise.jpg', ARRAY['Astro']::text[], null, 43),
  ('Star Trails', 'images/after-dark/startrails.jpg', 'https://fatni-photography.vercel.app/images/after-dark/startrails.jpg', ARRAY['Astro']::text[], null, 44),
  ('Tower Star Trails', 'images/astro/tower-star-trails.jpg', 'https://fatni-photography.vercel.app/images/astro/tower-star-trails.jpg', ARRAY['Astro']::text[], null, 45),
  ('Steel Wool Stars', 'images/after-dark/FIRE50edit.jpg', 'https://fatni-photography.vercel.app/images/after-dark/FIRE50edit.jpg', ARRAY['Urban']::text[], null, 46),
  ('Delivery Rider', 'images/street/delivery-rider.jpg', 'https://fatni-photography.vercel.app/images/street/delivery-rider.jpg', ARRAY['Street']::text[], null, 47),
  ('Sunburst Walk', 'images/street/sunburst-walk.jpg', 'https://fatni-photography.vercel.app/images/street/sunburst-walk.jpg', ARRAY['Street']::text[], null, 48),
  ('Union Jack Suit', 'images/street/union-jack-suit.jpg', 'https://fatni-photography.vercel.app/images/street/union-jack-suit.jpg', ARRAY['Street']::text[], null, 49),
  ('Quiet Hours', 'images/after-dark-cover.jpg', 'https://fatni-photography.vercel.app/images/after-dark-cover.jpg', ARRAY['After Dark']::text[], null, 50),
  ('Noodle Alley', 'images/lo-noodle-alley.jpg', 'https://fatni-photography.vercel.app/images/lo-noodle-alley.jpg', ARRAY['After Dark']::text[], null, 51),
  ('Rain Walk', 'images/after-dark/rain-walk.jpg', 'https://fatni-photography.vercel.app/images/after-dark/rain-walk.jpg', ARRAY['After Dark']::text[], null, 52),
  ('Night Corner', 'images/after-dark/2F2E8CA6-A1DB-44ED-8879-E56955B99845.jpg', 'https://fatni-photography.vercel.app/images/after-dark/2F2E8CA6-A1DB-44ED-8879-E56955B99845.jpg', ARRAY['Urban']::text[], null, 53),
  ('Path Light', 'images/after-dark/46DB8C35-3B6D-4D6C-A04B-C7D5507F76D2.jpg', 'https://fatni-photography.vercel.app/images/after-dark/46DB8C35-3B6D-4D6C-A04B-C7D5507F76D2.jpg', ARRAY['Street']::text[], null, 54),
  ('Rain Glass', 'images/after-dark/762BEA4B-8793-4C72-A0CE-9308A2A8E87A.jpg', 'https://fatni-photography.vercel.app/images/after-dark/762BEA4B-8793-4C72-A0CE-9308A2A8E87A.jpg', ARRAY['After Dark']::text[], null, 55),
  ('Red Door', 'images/after-dark/red-door.jpg', 'https://fatni-photography.vercel.app/images/after-dark/red-door.jpg', ARRAY['After Dark']::text[], null, 56),
  ('Fog Street', 'images/after-dark/fog-street.jpg', 'https://fatni-photography.vercel.app/images/after-dark/fog-street.jpg', ARRAY['After Dark']::text[], null, 57),
  ('Shared Umbrella', 'images/after-dark/shared-umbrella.jpg', 'https://fatni-photography.vercel.app/images/after-dark/shared-umbrella.jpg', ARRAY['Street']::text[], null, 58),
  ('Piccadilly Run', 'images/after-dark/piccadilly-run.jpg', 'https://fatni-photography.vercel.app/images/after-dark/piccadilly-run.jpg', ARRAY['Street']::text[], null, 59),
  ('Blue Poncho', 'images/after-dark/blue-poncho.jpg', 'https://fatni-photography.vercel.app/images/after-dark/blue-poncho.jpg', ARRAY['After Dark']::text[], null, 60),
  ('Path Lights', 'images/after-dark/path-lights.jpg', 'https://fatni-photography.vercel.app/images/after-dark/path-lights.jpg', ARRAY['After Dark']::text[], null, 62),
  ('Night Train', 'images/after-dark/night-train.jpg', 'https://fatni-photography.vercel.app/images/after-dark/night-train.jpg', ARRAY['After Dark']::text[], null, 64),
  ('La Lasagne', 'images/after-dark/la-lasagne.jpg', 'https://fatni-photography.vercel.app/images/after-dark/la-lasagne.jpg', ARRAY['After Dark']::text[], null, 65),
  ('Bus Stop', 'images/after-dark/bus-stop.jpg', 'https://fatni-photography.vercel.app/images/after-dark/bus-stop.jpg', ARRAY['After Dark']::text[], null, 66),
  ('Night Grocery', 'images/after-dark/night-grocery.jpg', 'https://fatni-photography.vercel.app/images/after-dark/night-grocery.jpg', ARRAY['After Dark']::text[], null, 67),
  ('Late Cafe', 'images/after-dark/late-cafe.jpg', 'https://fatni-photography.vercel.app/images/after-dark/late-cafe.jpg', ARRAY['Street']::text[], null, 68),
  ('Snowflake Window', 'images/after-dark/snowflake-window.jpg', 'https://fatni-photography.vercel.app/images/after-dark/snowflake-window.jpg', ARRAY['After Dark']::text[], null, 69),
  ('Moulin Rouge', 'images/after-dark/moulin-rouge.jpg', 'https://fatni-photography.vercel.app/images/after-dark/moulin-rouge.jpg', ARRAY['Urban']::text[], null, 70),
  ('Piccadilly Crowd', 'images/after-dark/piccadilly-crowd.jpg', 'https://fatni-photography.vercel.app/images/after-dark/piccadilly-crowd.jpg', ARRAY['Street']::text[], null, 71),
  ('Neon Coupe', 'images/after-dark/neon-coupe.jpg', 'https://fatni-photography.vercel.app/images/after-dark/neon-coupe.jpg', ARRAY['After Dark']::text[], null, 72),
  ('Fog Brake Lights', 'images/after-dark/fog-brake-lights.jpg', 'https://fatni-photography.vercel.app/images/after-dark/fog-brake-lights.jpg', ARRAY['Urban']::text[], null, 73),
  ('Fog Petrol', 'images/after-dark/fog-petrol.jpg', 'https://fatni-photography.vercel.app/images/after-dark/fog-petrol.jpg', ARRAY['After Dark']::text[], null, 74),
  ('Fog Walker', 'images/after-dark/fog-walker.jpg', 'https://fatni-photography.vercel.app/images/after-dark/fog-walker.jpg', ARRAY['After Dark']::text[], null, 75),
  ('Orange Lamp Fog', 'images/after-dark/orange-lamp-fog.jpg', 'https://fatni-photography.vercel.app/images/after-dark/orange-lamp-fog.jpg', ARRAY['After Dark']::text[], null, 76),
  ('Red Signal Fog', 'images/after-dark/red-signal-fog.jpg', 'https://fatni-photography.vercel.app/images/after-dark/red-signal-fog.jpg', ARRAY['After Dark']::text[], null, 77),
  ('Fog Station Pass', 'images/after-dark/fog-station-pass.jpg', 'https://fatni-photography.vercel.app/images/after-dark/fog-station-pass.jpg', ARRAY['Urban']::text[], null, 78),
  ('Rain Bus', 'images/after-dark/rain-bus.jpg', 'https://fatni-photography.vercel.app/images/after-dark/rain-bus.jpg', ARRAY['After Dark']::text[], null, 79),
  ('Tower Bridge Fog', 'images/after-dark/tower-bridge-fog.jpg', 'https://fatni-photography.vercel.app/images/after-dark/tower-bridge-fog.jpg', ARRAY['After Dark']::text[], null, 80),
  ('Spiral Stairs', 'images/monochrome/spiral-stairs.jpg', 'https://fatni-photography.vercel.app/images/monochrome/spiral-stairs.jpg', ARRAY['Monochrome']::text[], null, 82),
  ('Contortionist', 'images/monochrome/contortionist.jpg', 'https://fatni-photography.vercel.app/images/monochrome/contortionist.jpg', ARRAY['Monochrome']::text[], null, 83),
  ('One Poultry', 'images/monochrome/one-poultry.jpg', 'https://fatni-photography.vercel.app/images/monochrome/one-poultry.jpg', ARRAY['Monochrome']::text[], null, 84),
  ('Light Beams', 'images/monochrome/light-beams.jpg', 'https://fatni-photography.vercel.app/images/monochrome/light-beams.jpg', ARRAY['Monochrome']::text[], null, 85),
  ('Stair Light', 'images/monochrome/stair-light.jpg', 'https://fatni-photography.vercel.app/images/monochrome/stair-light.jpg', ARRAY['Monochrome']::text[], null, 86),
  ('Millipede Spiral', 'images/monochrome/millipede-spiral.jpg', 'https://fatni-photography.vercel.app/images/monochrome/millipede-spiral.jpg', ARRAY['Monochrome']::text[], null, 87),
  ('Blindfold Piano', 'images/monochrome/blindfold-piano.jpg', 'https://fatni-photography.vercel.app/images/monochrome/blindfold-piano.jpg', ARRAY['Monochrome']::text[], null, 88),
  ('Marina Viaduct', 'images/urban/marina-viaduct.jpg', 'https://fatni-photography.vercel.app/images/urban/marina-viaduct.jpg', ARRAY['Urban']::text[], null, 90);

select count(*) as photo_count from public.photos;